import HtmlMinifier from "html-minifier";
import Terser from "terser";

import {promises as fs} from "fs";

async function main() {
    try {
        const inputFilePath = process.argv[2];
        const outputFilePath = process.argv[3];
        const inputData = await fs.readFile(inputFilePath);
        const inputDataMinified = HtmlMinifier.minify(inputData.toString(), {
            caseSensitive: true,
            collapseBooleanAttributes: true,
            collapseInlineTagWhitespace: true,
            collapseWhitespace: true,
            conservativeCollapse: false,
            continueOnParseError: false,
            decodeEntities: true,
            html5: true,
            includeAutoGeneratedTags: false,
            keepClosingSlash: false,
            minifyCSS: true,
            minifyJS: (text) => Terser.minify(text).code,
            minifyURLs: true,
            preserveLineBreaks: false,
            preventAttributesEscaping: false,
            processConditionalComments: true,
            processScripts: true,
            quoteCharacter: "'",
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            removeEmptyElements: false,
            removeOptionalTags: true,
            removeRedundantAttributes: true,
            removeScriptTypeAttributes: true,
            removeStyleLinkTypeAttributes: true,
            removeTagWhitespace: false,
            sortAttributes: false,
            sortClassName: false,
            useShortDoctype: true
        });

        await fs.writeFile(outputFilePath, inputDataMinified);
    } catch (error) {
        console.error(error.message);

        process.exit(1);
    }
}

main();
